---
title: "Group Project"
output: html_notebook
---

```{r}
library(tidyverse)
raw_flights = read_tsv("../data/flight_edges.tsv")
city_data = read_csv("../data/GDP_city.csv")
```

```{r}
#Filters only flights from 2009
flights_09 = raw_flights %>% filter(`Fly Date` > 200900)
city_data = as.double(as.character(city_data$`2017 (GDP)`))
shortenedCityData = city_data %>% group_by(Tag) %>% summarize(`Destination City` = Tag, GDP = sum(`2017 (GDP)`))
```

```{r}
#Creates a new table with some summarized data
#flightsTo: Total number of flights to a destination city
#totalPassengers: Total number of passengers travelling to a city
#passengerDensity: Percentage of passengers to seats
destinationCityData = flights_09 %>% group_by(`Destination City`) %>% summarize(flightsTo = n(), totalPassengers = sum(Passengers), passengerDensity = (sum(Passengers)/sum(Seats))) %>% arrange(desc(flightsTo))

```
```{r}
mergedTables = destinationCityData %>% inner_join(shortenedCityData, by="Destination City")
mergedTables
```


